language: haskell
script: cabal configure --enable-tests --constraint 'optparse-applicative == 0.10.0'  && cabal build && cabal test
install: cabal install --only-dependencies --enable-tests --constraint 'optparse-applicative == 0.10.0'
ghc:
 - 7.6
 - 7.8 


